[package]
name = "eeprom-programmer"
description = "A program to interact with AT28C EEPROM chips"
homepage = "https://github.com/Grazen0/eeprom-programmer"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["display", "error", "from"] }
kinded = "0.5.0"
serialport = "4.7.3"
shlex = "2.0.1"
